workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              only: develop
          steps:
            - run: |
                gem install bundler
                bundle install
                heroku login -i
                heroku git:remote -a your-staging-app
                git push heroku $CIRCLE_SHA1:master
