version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: cimg/ruby:2.7.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            gem install bundler
            bundle install
      - run:
          name: Run Tests
          command: |
            bundle exec rspec

  build-deploy:
    steps:
      - build
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              only: develop
          steps:
            - run: |
                # Install dependencies
                gem install bundler
                bundle install

                # Log in to Heroku
                heroku login -i

                # Set remote for staging app
                heroku git:remote -a your-staging-app

                # Deploy to staging
                git push heroku $CIRCLE_SHA1:master
