# .circleci/config.yml

version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: cimg/ruby:2.7.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            gem install bundler
            bundle instal
      - run:
          name: Run Tests
          command: |
            bundle exec rspec
        - run:
          name: Deploy
          command: |
            heroku login -i
            heroku git:remote -a your-staging-app
            git push heroku $CIRCLE_SHA1:master
        
